### ISSUE TITLE
Easily Accessible Bank Enable/Disable toggle in Dropdown (Interim Workaround For Lack of Warbank)

### ISSUE THREAD

**Issue by Ketrel** [gsnerf/Baud-Bag#12]
As seen here

![image](https://github.com/user-attachments/assets/a6189a71-deec-4dd4-a6cc-9add336abed3)

(Based off the Develop branch)

**Comment by Ketrel** [comment]
(To avoid having to go through the options menu when you need to toggle it off/on)

**Comment by gsnerf** [comment]
Thanks for the PR.

I'm currently working on adding the warbank. If I find that I cannot add it shortly, I will consider merging your PR as an interims solution.

**Comment by gsnerf** [comment]
Will be in next release, which should arrive shortly.

**Comment by gsnerf** [comment]
Released with 11.0.2.1.

Was in a rush because of breaking issues, so I forgot the mention in the changelog 😨 will fix that with the next release!
