### ISSUE TITLE
Overrides.lua:105: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Tiiara** [gsnerf/Baud-Bag#16]
I'm not entirely sure what this error does, as it doesn't seem to break anything, but still, it does pop up on every log in. 

```lua
73x BaudBag/Overrides.lua:105: attempt to index field '?' (a nil value)
[string "@BaudBag/Overrides.lua"]:105: in function <BaudBag/Overrides.lua:100>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:2025: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:2008>
[string "=[C]"]: in function `CloseAllBags'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:1128: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:1127>
[string "=[C]"]: in function `securecall'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2853: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:2792>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleGameMenu'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:253: in function `TransitionBackOpeningPanel'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:242: in function `ExitWithCommit'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:211: in function `Close'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:54: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:53>

Locals:
(*temporary) = nil
(*temporary) = 5
(*temporary) = 1
(*temporary) = 5
(*temporary) = 5
(*temporary) = "attempt to index field '?' (a nil value)"
AddOnTable = <table> {
 Cache = <table> {
 }
 Backgrounds = <table> {
 }
 Functions = <table> {
 }
 Config = <table> {
 }
 Events = <table> {
 }
 ContainerIdOptionsIndexMap = <table> {
 }
 SubBags = <table> {
 }
 Sets = <table> {
 }
 State = <table> {
 }
 BlizzAPI = <table> {
 }
 BlizzConstants = <table> {
 }
 Localized = <table> {
 }
}

```

**Comment by gsnerf** [comment]
Hmm which flavor are we talking about? Retail? Is that the only error or are there more?

It seems like default UI is calling ContainerFrame.CloseAllBags at a very strange time, when baudbag isn't fully loaded yet, but I haven't been able to reproduce that yet. Maybe the combination with some other addons that trigger something in the bags...

**Comment by Tiiara** [comment]
Yes, it's retail. English Client. 
Let me try some addon combinations and get back to you in a few.

**Comment by Tiiara** [comment]
I think I found the culprit. It's the addon [ItemLevelDisplay](https://www.curseforge.com/wow/addons/itemleveldisplay/)

When I load both baudbag and itemleveldisplay (**with** or **without** their _ItemLevelDisplay-Baudbag_ option) the error occurs. 


BaudBag 11.0.2.3
ItemLevelDisplay 2.10.2

![ItemLevelDisplay](https://github.com/user-attachments/assets/75c1019e-a4e8-4708-8f99-bbc10d8859bd)

**Comment by gsnerf** [comment]
okay I will have a look if there is anything reasonable that I can do

**Comment by gsnerf** [comment]
Btw, baud bag has itel level support integrated since some versions, so you might not necessarily need that addon. It has some issues since a recent Patch though.

**Comment by gsnerf** [comment]
In the meantime I did rework how the overrides are being registered with the result (I hope) that these methods will only be called when the addon is actually ready to handle them. I'm not sure if this will mess with the function of ItemLevelDisplay yet, but don't think so. Will be available with the next release.

**Comment by gsnerf** [comment]
This should be gone with v11.0.2.6
