### ISSUE TITLE
Merge pull request for Caerdon Wardrobe fixes

### ISSUE THREAD

**Issue by Caerdon** [gsnerf/Baud-Bag#2]
I'm the author of Caerdon Wardrobe.  I've been getting a few complaints about it not working with Baud Bag, and I discovered that some code had been included in Baud Bag to work with my addon (which is great)!  It was having some issues, so I made a pull request to resolve the issues and get the addons working together again.

Any chance we can see it in a release soon?

https://github.com/gsnerf/Baud-Bag/pull/1

Thanks!

**Comment by gsnerf** [comment]
Sorry for the late anwer, somehow I didn't get notified about the issue. I'll have a look at it shortly!

**Comment by Caerdon** [comment]
No worries.  I figured it was probably something like that but wasn’t sure how to reach out.  :)  I actually went ahead and brought support for Baud Bag (and a bunch of others) directly into Caerdon Wardrobe, so you can probably just remove the integration.

**Comment by gsnerf** [comment]
If that's the case, then that's what I'll do :) If you need any more hooks let me know, I'll try to keep you posted if I have to make changes to the existing ones.

**Comment by gsnerf** [comment]
Removed custom support with v8.0.3
