### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by xuanguashoulei** [gsnerf/Baud-Bag#21]
Why is there no BaudBag-Wrath.toc in BaudBag-v11.0.0.1, which makes it unusable for me

**Comment by xuanguashoulei** [comment]
3.4.3

**Comment by gsnerf** [comment]
Hi,

I had to remove tocs targetting wrath, because the build scripts used can't handle builds targetting "non-existent" classic versions. The cataclysm classic version however should be fully compatible, you just have to ensure that "outdated versions" are loaded in the addons screen of wow.
