### ISSUE TITLE
LUA error in new build

### ISSUE THREAD

**Issue by Thrayl** [gsnerf/Baud-Bag#3]
Using new build release today (v9.0,3) getting the following LUA error on load:

![image](https://user-images.githubusercontent.com/68885894/96848432-28fe2800-14a0-11eb-938c-6b3de9629ed7.png)

**Comment by gsnerf** [comment]
I'm sorry but somehow I didn't get any notifications about this issue (again). As this version is pretty old and thus not functional, I will close it. If you still experience something similar please open a new issue here or on the curseforge project page (I will try to fix the notifications here).
