### ISSUE TITLE
Ability to disable the opening animation

### ISSUE THREAD

**Issue by WerDei** [gsnerf/Baud-Bag#4]
I'd love to see the option to disable the fade-in animation of the bag. Having an opening animation makes it inconsistent with other parts of the WoW inteface, as well as makes it take a bit longer to start to look for an item I need.

**Comment by gsnerf** [comment]
Hey, sorry for the long time, I somehow didn't get any kinds of notifications about the issues here. I will take a look, although the fade animations are so short that it should hardly matter.

**Comment by WerDei** [comment]
Thanks for considering it anyway! It was a while since I've used this addon (or played wow for that matter), but I remember I've found a single variable in the code and set it to 0 to remove the animation, so I feel it'd be rather straightforward to implement.

**Comment by gsnerf** [comment]
I have added a configuration option to enable the animation and disabled it by default, to have the window behavior consistent with default UI. Will be released with 10.0.2.5
