### ISSUE TITLE
Close button is offset

### ISSUE THREAD

**Issue by cremor** [gsnerf/Baud-Bag#7]
The close buttons on the bags are not exactly in place.
The + button that opens the dropdown menu also overlaps with the border to the close button area.

![grafik](https://user-images.githubusercontent.com/116314/202751107-e9e13a82-9a0a-4fbc-bfd2-d911cd7be308.png)

Might be related to a non default UI scale. Mine is set to 84%.

**Comment by gsnerf** [comment]
This is related to the changed default UI elements with Dragonflight. I'm using the default close button which looked different previously. I will fix it, but it has a lower priority because it doesn't affect functionalit (unlike some other issues I'm still seeing).

**Comment by gsnerf** [comment]
Fixed with upcoming release.

**Comment by cremor** [comment]
Fixed in 10.0.2.11, thanks.
